# Generated by Django 3.0.12 on 2021-03-16 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_translations'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='cciidd',
            field=models.IntegerField(null=True),
        ),
    ]
